### ISSUE TITLE
Have you managed to use the module inside a ng library.

### ISSUE THREAD

**Issue by dlebee** [TryHardDood/ngx-fomantic-ui#6]
Hello it seems you have taken interest in keeping this project alive.

I was wondering if you managed to use the project in a reusable library.

Steps to reproduce the issue:

``` 
ng new my-fomantic
npm i ngx-fomantic-ui
ng generate library my-fomantic --prefix mysui
```

I used this in the template of the generated component inside the projects/my-fomantic/lib/component...

```<sui-checkbox [(ngModel)]="checked"></sui-checkbox>```

Obviously the SuiModule imported was added to the reusable Module.

When tring to build the reusably library to publish it on npm, it seems to attempt a AOT compilation, and everything kind of fails from there.

``` 
ng build my-fomantic
```

I get some errors that look like the following:

```
BUILD ERROR
projects/poweredsoft/ngx-semantic-ui/src/lib/ngx-semantic-ui.component.ts.NgxSemanticUiComponent.html(2,5): : Directive ɵk, Expecte
d 0 arguments, but got 1.

Error: projects/poweredsoft/ngx-semantic-ui/src/lib/ngx-semantic-ui.component.ts.NgxSemanticUiComponent.html(2,5): : Directive ɵk, 
Expected 0 arguments, but got 1.

    at Object.<anonymous> (/Users/dlebee/Test/ngx-semantic-ui/node_modules/ng-packagr/lib/ngc/compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dlebee/Test/ngx-semantic-ui/node_modules/ng-packagr/lib/ngc/compile-source-files.js:4:58)
```

**Comment by benjaminforras** [comment]
Hello!
I did not look into resuable libraries, yet.
My priorities right now is to bring semantic ui / fomantic ui changes to this fork.

I'll look into this problem as soon as I have time. 
Also, if anybody wants to help, feel free to submit a pull request.

**Comment by benjaminforras** [comment]
**Thanks for filing an issue, it is fixed now.**

To use the fix, please install the latest version using the command below:
`npm install ngx-fomantic-ui@next`

If you face any issue, feel free to open a new issue. Thanks!

**Comment by dlebee** [comment]
@TryHardDood Thank you, for taking care of this.

I would gladly help, fixing other same kind of issues with AOT Compilations, if we have a change to discuss the details on what needs to be done :)

I'd be happy to collaborate on the project since I like the ui of semantic ui, and I wouldn't want it to disapear.

David.

**Comment by benjaminforras** [comment]
Great to hear 😄 
Come on gitter and let's discuss: https://gitter.im/ngx-fomantic-ui/development
